//!
//! **Generated by `scripts/gen_manifest.py` from
//! `../river-py/manifest.json`.  Do not edit by hand** -- run
//! `make manifest-regen`, and `make manifest-check` to verify the
//! checked-in copy still matches the reference.
//!
//! Everything here is a value the two implementations must agree on
//! *exactly* or they produce different bytes, and none of it is
//! stated by the paper:
//!
//! * **`(sigma_num, sigma_den)`** per Gaussian field.  The paper's
//!   widths are irrational, so every implementation pins some
//!   rational; the reference pins `round_ties_even(sigma * 2^20)`.
//!   The rounding removes only the *final* float error, so the input
//!   has to be computed in the same operation order -- which is
//!   exactly the fragility this table removes from the build.
//! * **`rice_k`** per Gaussian field.  `k = floor(log2(sqrt(2 ln 2)
//!   sigma))` is wire-visible, and one off is a different encoding
//!   rather than a rounding difference.
//! * **`bound`** per response field: the largest coefficient that can
//!   pass verification, `floor(sqrt(bound_sq))` -- exact, so the
//!   encoder's cap and the acceptance test cannot disagree.
//! * **`width`** per fixed-width field, in bits.
//!
//! The module's own tests re-derive every entry from
//! [`crate::params`] and the coders, so a divergence between this
//! table and the code that consumes it fails here rather than as
//! "proof bytes differ" in a cross-language vector.

#![allow(non_upper_case_globals)]

/// Denominator every pinned Gaussian width shares: `2^20`.
pub const SIGMA_DEN: u64 = 1048576;
/// Fixed-point width of the rejection-sampling acceptance test.
pub const PROB_BITS: u32 = 192;
/// Where the Gaussian proposal is truncated, in units of sigma.
pub const GAUSSIAN_TAILCUT: u64 = 14;
/// Verifier bound multiplier: `6 sigma`.
pub const VERIFIER_TAILCUT: u64 = 6;
/// `sqrt(2 ln 2)` to 30 significant figures, as an exact rational.
///
/// The Rice parameter is `floor(log2(sqrt(2 ln 2) sigma))` and `k` is
/// wire-visible, so *some* rational stands in for the irrational
/// constant; what matters is that the standing-in never moves `k`.
/// Thirty digits makes the window in which it could `1e-30` wide, and
/// a test measures the actual distance to the nearest boundary at
/// every field of every profile.
pub const RICE_CONST_NUM_DEC: &str = "1177410022515474691011569326460";
pub const RICE_CONST_DEN_DEC: &str = "1000000000000000000000000000000";

/// One Rice-coded Gaussian field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GaussianSpec {
    /// Numerator of the pinned width; the denominator is [`SIGMA_DEN`].
    pub sigma_num: u64,
    pub sigma_den: u64,
    /// `floor(log2(sqrt(2 ln 2) sigma))`.
    pub rice_k: u32,
    /// Largest coefficient that can pass verification.
    pub bound: i64,
    /// Longest unary run a decoder may accept: `(bound >> k) + 1`.
    pub max_high: u64,
}

/// One fixed-width signed field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SignedSpec {
    pub bound: i64,
    pub width: u32,
}

/// The exact layer's frozen dimensions and its one Gaussian field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExactSpec {
    /// Backend the sizes below were measured against.
    pub backend: &'static str,
    pub d_tilde: usize,
    pub l_split: usize,
    pub q_tilde: u64,
    /// `n~ + l~ + N_ex + alpha`.
    pub kappa: usize,
    /// `l~`: rows of `t_0` and width of `B_0`'s identity block.
    pub identity_rank: usize,
    /// `n~`: the shared random tail every `b_i` draws from.
    pub tail_rank: usize,
    /// `kappa - l~`: the part of the opening actually transmitted.
    pub response_rank: usize,
    /// Message ring elements, one per 64-slot block.
    pub n_ex: usize,
    pub block_slots: usize,
    pub block_used: usize,
    pub radix_weights: [i64; 4],
    /// `y_eval`, the one Gaussian field in the exact proof.
    pub y_eval: GaussianSpec,
    /// `|W|`, which is all uniform and therefore exact.
    pub w_bytes: usize,
    /// Worst-case `|pi_ex|`; Rice makes the real length vary.
    pub proof_bytes_max: usize,
}

/// Every wire-visible numeric choice for one profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProfileManifest {
    pub profile: &'static str,
    /// High bits of the selector commitment `B`.  Signed since the
    /// The paper takes `[[.]]_K` on the centred representative.
    pub b_hi: SignedSpec,
    pub x: SignedSpec,
    pub f1: GaussianSpec,
    pub zb: GaussianSpec,
    pub zs: GaussianSpec,
    pub zm: GaussianSpec,
    /// Row counts of the OOM layout, in wire order after `x`.
    pub rows: OomRows,
    /// Worst-case and best-case `|pi_OOM|`.
    pub oom_max_bytes: usize,
    pub oom_min_bytes: usize,
    pub exact: ExactSpec,
}

/// Row counts of every multi-row OOM field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OomRows {
    pub b_hi: usize,
    pub f1: usize,
    pub zb: usize,
    pub zs: usize,
    pub zm: usize,
}

/// The OOM layout's field order on the wire.
pub const OOM_FIELD_ORDER: [&str; 6] = ["B", "x", "f1", "zb", "zs", "zm"];

/// The framing every proof carries: two length-prefixed blocks.
pub const FRAMING_PREFIX_BYTES: usize = 4;
pub const FRAMING_TOTAL_BYTES: usize = 8;
pub const FRAMING_BLOCK_ORDER: [&str; 2] = ["oom", "exact"];

/// Frozen wire manifest for `RiVeR-N8`.
pub const N8: ProfileManifest = ProfileManifest {
    profile: "RiVeR-N8",
    b_hi: SignedSpec {
        bound: 137438953472,
        width: 39,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 4294967296,
        sigma_den: 1048576,
        rice_k: 12,
        bound: 24576,
        max_high: 7,
    },
    zb: GaussianSpec {
        sigma_num: 41195879100,
        sigma_den: 1048576,
        rice_k: 15,
        bound: 235724,
        max_high: 8,
    },
    zs: GaussianSpec {
        sigma_num: 23450521436160,
        sigma_den: 1048576,
        rice_k: 24,
        bound: 134184960,
        max_high: 8,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 42,
        f1: 7,
        zb: 46,
        zs: 98,
        zm: 1,
    },
    oom_max_bytes: 24608,
    oom_min_bytes: 19772,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Frozen wire manifest for `RiVeR-N16`.
pub const N16: ProfileManifest = ProfileManifest {
    profile: "RiVeR-N16",
    b_hi: SignedSpec {
        bound: 549755813891,
        width: 41,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 5368709120,
        sigma_den: 1048576,
        rice_k: 12,
        bound: 30720,
        max_high: 8,
    },
    zb: GaussianSpec {
        sigma_num: 42518007000,
        sigma_den: 1048576,
        rice_k: 15,
        bound: 243289,
        max_high: 8,
    },
    zs: GaussianSpec {
        sigma_num: 20044203299842,
        sigma_den: 1048576,
        rice_k: 24,
        bound: 114693851,
        max_high: 7,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 43,
        f1: 15,
        zb: 49,
        zs: 100,
        zm: 1,
    },
    oom_max_bytes: 25960,
    oom_min_bytes: 21080,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Frozen wire manifest for `RiVeR-N64`.
pub const N64: ProfileManifest = ProfileManifest {
    profile: "RiVeR-N64",
    b_hi: SignedSpec {
        bound: 2199023255552,
        width: 43,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 4563402752,
        sigma_den: 1048576,
        rice_k: 12,
        bound: 26112,
        max_high: 7,
    },
    zb: GaussianSpec {
        sigma_num: 43377043416,
        sigma_den: 1048576,
        rice_k: 15,
        bound: 248205,
        max_high: 8,
    },
    zs: GaussianSpec {
        sigma_num: 21646635171840,
        sigma_den: 1048576,
        rice_k: 24,
        bound: 123863040,
        max_high: 8,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 50,
        f1: 63,
        zb: 51,
        zs: 98,
        zm: 1,
    },
    oom_max_bytes: 31616,
    oom_min_bytes: 25052,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Frozen wire manifest for `RiVeR-N128`.
pub const N128: ProfileManifest = ProfileManifest {
    profile: "RiVeR-N128",
    b_hi: SignedSpec {
        bound: 2199023255552,
        width: 43,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 3221225472,
        sigma_den: 1048576,
        rice_k: 11,
        bound: 18432,
        max_high: 10,
    },
    zb: GaussianSpec {
        sigma_num: 43377043416,
        sigma_den: 1048576,
        rice_k: 15,
        bound: 248205,
        max_high: 8,
    },
    zs: GaussianSpec {
        sigma_num: 30822128908419,
        sigma_den: 1048576,
        rice_k: 25,
        bound: 176365636,
        max_high: 6,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 50,
        f1: 127,
        zb: 51,
        zs: 99,
        zm: 1,
    },
    oom_max_bytes: 37488,
    oom_min_bytes: 28368,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Frozen wire manifest for `RiVeR-N256`.
pub const N256: ProfileManifest = ProfileManifest {
    profile: "RiVeR-N256",
    b_hi: SignedSpec {
        bound: 4398046511104,
        width: 44,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 2952790016,
        sigma_den: 1048576,
        rice_k: 11,
        bound: 16896,
        max_high: 9,
    },
    zb: GaussianSpec {
        sigma_num: 43800244105,
        sigma_den: 1048576,
        rice_k: 15,
        bound: 250627,
        max_high: 8,
    },
    zs: GaussianSpec {
        sigma_num: 36625772743250,
        sigma_den: 1048576,
        rice_k: 25,
        bound: 209574352,
        max_high: 7,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 49,
        f1: 255,
        zb: 52,
        zs: 101,
        zm: 1,
    },
    oom_max_bytes: 48512,
    oom_min_bytes: 34808,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Frozen wire manifest for `RiVeR-TOY`.
pub const TOY: ProfileManifest = ProfileManifest {
    profile: "RiVeR-TOY",
    b_hi: SignedSpec {
        bound: 17179869181,
        width: 35,
    },
    x: SignedSpec {
        bound: 16,
        width: 6,
    },
    f1: GaussianSpec {
        sigma_num: 4294967296,
        sigma_den: 1048576,
        rice_k: 12,
        bound: 24576,
        max_high: 7,
    },
    zb: GaussianSpec {
        sigma_num: 12148002000,
        sigma_den: 1048576,
        rice_k: 13,
        bound: 69511,
        max_high: 9,
    },
    zs: GaussianSpec {
        sigma_num: 7490994291296,
        sigma_den: 1048576,
        rice_k: 23,
        bound: 42863813,
        max_high: 6,
    },
    zm: GaussianSpec {
        sigma_num: 2915520479977,
        sigma_den: 1048576,
        rice_k: 21,
        bound: 16682742,
        max_high: 8,
    },
    rows: OomRows {
        b_hi: 4,
        f1: 3,
        zb: 4,
        zs: 10,
        zm: 1,
    },
    oom_max_bytes: 2512,
    oom_min_bytes: 2012,
    exact: ExactSpec {
        backend: "opening",
        d_tilde: 256,
        l_split: 64,
        q_tilde: 67107713,
        kappa: 17,
        identity_rank: 4,
        tail_rank: 4,
        response_rank: 13,
        n_ex: 6,
        block_slots: 64,
        block_used: 32,
        radix_weights: [1, 3, 9, 17],
        y_eval: GaussianSpec {
            sigma_num: 2915520479977,
            sigma_den: 1048576,
            rice_k: 21,
            bound: 16698102,
            max_high: 8,
        },
        w_bytes: 8320,
        proof_bytes_max: 9584,
    },
};

/// Every profile, in the order [`crate::params::PROFILES`] lists them.
pub const MANIFEST: [ProfileManifest; 6] = [N8, N16, N64, N128, N256, TOY];

/// The frozen manifest for a set of parameters, or `None`.
///
/// **This is the one production may use.**  It matches the *whole*
/// canonical profile, not its name: a caller can build a
/// `RiVeRParams` that says `"RiVeR-N8"` and carries a different
/// `ell`, and handing that one N8's frozen widths would make it
/// sample at N8 while `check()` validated the modified fields — a
/// sampler and a bound derived from different profiles, with
/// nothing to notice.
///
/// A profile that does not match exactly gets `None`, and the
/// caller derives instead: slower to reason about, but always
/// consistent with the parameters in hand.
pub fn for_params(par: &crate::params::RiVeRParams) -> Option<&'static ProfileManifest> {
    let canonical = crate::params::get(par.name)?;
    if canonical != *par {
        return None;
    }
    MANIFEST.iter().find(|m| m.profile == par.name)
}

/// The frozen manifest for a profile *name*.
///
/// For tests and tooling that already hold a canonical profile.
/// Production wants [`for_params`], which checks that the name and
/// the parameters agree.
pub fn for_profile(name: &str) -> Option<&'static ProfileManifest> {
    MANIFEST.iter().find(|m| m.profile == name)
}

// =========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codec::{optimal_rice_k, Coder};
    use crate::exact::ExactParams;
    use crate::params::{self, RiVeRParams};
    use crate::sample::rational_sigma;

    fn params_for(m: &ProfileManifest) -> RiVeRParams {
        params::get(m.profile).unwrap_or_else(|| panic!("no profile {}", m.profile))
    }

    #[test]
    fn every_profile_has_a_manifest_entry() {
        let mut names: Vec<&str> = params::PROFILES.iter().map(|p| p.name).collect();
        let mut listed: Vec<&str> = MANIFEST.iter().map(|m| m.profile).collect();
        names.sort_unstable();
        listed.sort_unstable();
        assert_eq!(names, listed);
    }

    /// The pinned rationals are what `rational_sigma` produces from the
    /// profile's own float width, in the reference's operation order.
    ///
    /// This is the check that lets production read the table instead of
    /// re-deriving `round_ties_even(sigma * 2^20)` from an `f64` chain:
    /// if the chain ever moves, this fails here rather than as a byte
    /// difference in a cross-language vector.
    #[test]
    fn gaussian_widths_rederive_from_the_parameters() {
        for m in MANIFEST {
            let p = params_for(&m);
            for (label, spec, sigma) in [
                ("f1", m.f1, p.sigma_a()),
                ("zb", m.zb, p.sigma_b()),
                ("zs", m.zs, p.sigma_s()),
                ("zm", m.zm, p.sigma_m()),
                ("y_eval", m.exact.y_eval, p.sigma_m()),
            ] {
                assert_eq!(
                    rational_sigma(sigma),
                    (spec.sigma_num, spec.sigma_den),
                    "{} {label}",
                    m.profile
                );
                assert_eq!(spec.sigma_den, SIGMA_DEN, "{} {label}", m.profile);
            }
        }
    }

    /// `k = floor(log2(sqrt(2 ln 2) sigma))`, over the exact rational.
    #[test]
    fn rice_parameters_rederive_from_the_pinned_widths() {
        for m in MANIFEST {
            for (label, spec) in [
                ("f1", m.f1),
                ("zb", m.zb),
                ("zs", m.zs),
                ("zm", m.zm),
                ("y_eval", m.exact.y_eval),
            ] {
                assert_eq!(
                    optimal_rice_k(spec.sigma_num, spec.sigma_den),
                    spec.rice_k,
                    "{} {label}",
                    m.profile
                );
            }
        }
    }

    /// No field's Rice parameter sits near a power-of-two boundary, so
    /// the 30-digit stand-in for `sqrt(2 ln 2)` cannot move one.
    ///
    /// Measured rather than assumed: the margin is the distance from
    /// `sqrt(2 ln 2) sigma` to the nearest power of two, relative.
    #[test]
    fn rice_parameters_are_far_from_a_boundary() {
        let c = (2.0f64 * 2.0f64.ln()).sqrt();
        for m in MANIFEST {
            for (label, spec) in [
                ("f1", m.f1),
                ("zb", m.zb),
                ("zs", m.zs),
                ("zm", m.zm),
                ("y_eval", m.exact.y_eval),
            ] {
                let sigma = spec.sigma_num as f64 / spec.sigma_den as f64;
                let v = c * sigma;
                let lo = (2f64).powi(spec.rice_k as i32);
                let hi = 2.0 * lo;
                let margin = ((v - lo) / lo).min((hi - v) / hi);
                assert!(
                    margin > 1e-3,
                    "{} {label}: sqrt(2 ln 2) sigma = {v} is {margin} from a \\
                     boundary at k = {}",
                    m.profile,
                    spec.rice_k
                );
            }
        }
    }

    /// Each bound is the largest coefficient the verifier can accept —
    /// `floor(sqrt(bound_sq))` — so the encoder's cap and the acceptance
    /// test agree by construction.
    #[test]
    fn bounds_are_the_largest_value_that_can_pass() {
        for m in MANIFEST {
            let p = params_for(&m);
            for (label, bound, sq) in [
                ("f1", m.f1.bound, p.f1_inf_bound_sq()),
                ("zb", m.zb.bound, p.zb_inf_bound_sq()),
                ("zs", m.zs.bound, p.zs_inf_bound_sq()),
                ("zm", m.zm.bound, p.zm_inf_bound_sq()),
            ] {
                assert_eq!(sq.floor_sqrt() as i64, bound, "{} {label}", m.profile);
                let b = bound as u128;
                assert!(
                    !sq.exceeded_by(b * b),
                    "{} {label}: bound rejected",
                    m.profile
                );
                let n = b + 1;
                assert!(
                    sq.exceeded_by(n * n),
                    "{} {label}: bound+1 accepted",
                    m.profile
                );
            }
            // `x` is the challenge, bounded by `gamma` rather than by a
            // Gaussian tail.
            assert_eq!(m.x.bound, p.gamma as i64, "{} x", m.profile);
            // `y_eval` is *not* bounded by `6 sigma_m`: it is
            // `z_eval - x e_eval`, so an accepted transcript reaches
            // `6 sigma_m + ||x||_1 ||e_eval||_inf`.
            assert_eq!(
                m.exact.y_eval.bound,
                m.zm.bound + (p.w as u64 * p.gamma * p.B_e()) as i64,
                "{} y_eval",
                m.profile
            );
        }
    }

    /// Every fixed-width field is exactly as wide as its bound needs.
    #[test]
    fn fixed_widths_rederive_from_their_bounds() {
        for m in MANIFEST {
            for (label, spec) in [("B", m.b_hi), ("x", m.x)] {
                match Coder::signed(spec.bound) {
                    Coder::Signed { width, bound } => {
                        assert_eq!(width, spec.width, "{} {label} width", m.profile);
                        assert_eq!(bound, spec.bound, "{} {label} bound", m.profile);
                    }
                    other => panic!("{} {label}: {other:?}", m.profile),
                }
            }
        }
    }

    /// The longest unary run a decoder may accept, `(bound >> k) + 1`.
    #[test]
    fn max_high_matches_the_coder() {
        for m in MANIFEST {
            for (label, spec) in [
                ("f1", m.f1),
                ("zb", m.zb),
                ("zs", m.zs),
                ("zm", m.zm),
                ("y_eval", m.exact.y_eval),
            ] {
                assert_eq!(
                    spec.max_high,
                    (spec.bound >> spec.rice_k) as u64 + 1,
                    "{} {label}",
                    m.profile
                );
            }
        }
    }

    /// The exact layer's frozen dimensions are the ones `ExactParams`
    /// derives — including the two ranks whose roles have been reversed
    /// twice, which are both 4 here and so cannot be told apart by
    /// a numeric comparison of the constants alone.
    #[test]
    fn exact_dimensions_match_the_parameters() {
        for m in MANIFEST {
            let ex = ExactParams::new(&params_for(&m)).expect("exact params");
            assert_eq!(ex.d_tilde(), m.exact.d_tilde, "{}", m.profile);
            assert_eq!(ex.l_split(), m.exact.l_split, "{}", m.profile);
            assert_eq!(ex.q_tilde(), m.exact.q_tilde, "{}", m.profile);
            assert_eq!(ex.kappa(), m.exact.kappa, "{}", m.profile);
            assert_eq!(ex.t0_rows(), m.exact.identity_rank, "{}", m.profile);
            assert_eq!(ex.tail_rank(), m.exact.tail_rank, "{}", m.profile);
            assert_eq!(ex.response_rank(), m.exact.response_rank, "{}", m.profile);
            assert_eq!(ex.n_ex(), m.exact.n_ex, "{}", m.profile);
            assert_eq!(ex.block_slots(), m.exact.block_slots, "{}", m.profile);
            assert_eq!(ex.block_used(), m.exact.block_used, "{}", m.profile);
            assert_eq!(crate::exact::RADIX_WEIGHTS, m.exact.radix_weights);
        }
    }

    /// A profile that merely *says* it is `RiVeR-N8` does not get N8's
    /// frozen widths.
    ///
    /// `for_profile` matches on the name alone, which is fine for a test
    /// holding a canonical profile and is a hazard in production: a
    /// modified profile would sample at the frozen widths while every
    /// bound came from its own fields — a sampler and an acceptance test
    /// derived from different parameter sets.  `for_params` is what the
    /// codec, the OOM layer and the exact backend call.
    #[test]
    fn a_modified_profile_does_not_inherit_its_namesakes_manifest() {
        for canonical in params::PROFILES {
            assert!(
                for_params(&canonical).is_some(),
                "{} lost its own manifest",
                canonical.name
            );
            // One field at a time, each of them wire-visible.
            let mutations: [fn(&mut RiVeRParams); 6] = [
                |p| p.ell += 1,
                |p| p.n += 1,
                |p| p.k_hat += 1,
                |p| p.n_hat += 1,
                |p| p.phi_s += 1,
                |p| p.gamma += 1,
            ];
            for mutate in mutations {
                let mut modified = canonical;
                mutate(&mut modified);
                assert_eq!(modified.name, canonical.name, "the name is unchanged");
                assert!(
                    for_params(&modified).is_none(),
                    "{}: a modified profile kept the frozen manifest",
                    canonical.name
                );
                // and the name-keyed lookup still answers, which is why
                // production must not use it
                assert!(for_profile(modified.name).is_some());
            }
        }
    }
}
